version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ${MODELS_DIRECTORY}:/root/.ollama/models  # Use env variable
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: rig_v2
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"  # Adjust based on your app's port
    volumes:
      - ${PROJECT_DIRECTORY}:${PROJECT_DIRECTORY}
        #      - ${GPT_MODEL_PATH}:${GPT_MODEL_PATH}
        #      - ${RAG_MODEL_PATH}:${RAG_MODEL_PATH}
      - ${RULE_TYPES_DIRECTORY}:${RULE_TYPES_DIRECTORY}
volumes:
  ollama_data: